### ISSUE TITLE
dates are not clickable

### ISSUE THREAD

**Issue by pmalikbtech** [nikhil-001mehta/angular-2-daterangepicker#29] opened 2018-05-07 12:47 UTC
dates are not clickable and not updated in view

**Comment by nikhil-001mehta** [comment] 2018-05-07 15:39
Yes there was a issue that month was not getting updates on left calendar which I resolved in v1.1.36. But I found that dates are clickable. It will be mor helpful if you can provide more insights

**Comment by pmalikbtech** [comment] 2018-05-09 09:35
on init every time getting error (ERROR TypeError: Cannot read property 'startDate' of undefined). but i am passing options having start date and end date. by default its picking up today date in both input fields

**Comment by nikhil-001mehta** [comment] 2018-05-09 13:59
@pmalikbtech Can you please post options you are passing to the daterangepicker component. It will help me to figure out what is the exact issue. Thanks

**Comment by nikhil-001mehta** [comment] 2018-05-18 19:27
closing the issue as thread is inactive for more than a week. And no other user has raised same issue.

**Closed by nikhil-001mehta** 2018-05-18 19:27 UTC

**Comment by sapanjwani** [comment] 2018-06-15 06:49
Hey , i think i'm facing the similar issue. Can we sort this out ?

**Comment by sapanjwani** [comment] 2018-06-16 10:03
Hi Nikhil,

I was using on Chrome , actually , it works good when I give min date and
max date in option but else does not .

I was looking into code of daterangepicker-component.ts, you return moment
() somewhere , I guess the issue is happening due to checks.

To replicate, give no option , it should work by taking default values of
options. But it was not , dates were not clickable .

Regards,
Saurabh

On 16-Jun-2018 2:55 PM, "nikhil.001mehta" <notifications@github.com> wrote:

@sapanjwani <https://github.com/sapanjwani> can you please let me know
which browser are you using

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nikhil-001mehta/angular-2-daterangepicker/issues/29#issuecomment-397800238>,
or mute the thread

**Comment by sapanjwani** [comment] 2018-06-16 10:13
Hi,

You can reach me @9773671145 in case a discussion is needed , maybe it's
something I'm doing wrong , and you could help me out .

Regards,
Saurabh

On 16-Jun-2018 3:33 PM, "saurabh panjwani" <saurabh110693@gmail.com> wrote:

Hi Nikhil,

I was using on Chrome , actually , it works good when I give min date and
max date in option but else does not .

I was looking into code of daterangepicker-component.ts, you return moment
() somewhere , I guess the issue is happening due to checks.

To replicate, give no option , it should work by taking default values of
options. But it was not , dates were not clickable .

Regards,
Saurabh

On 16-Jun-2018 2:55 PM, "nikhil.001mehta" <notifications@github.com> wrote:

@sapanjwani <https://github.com/sapanjwani> can you please let me know
which browser are you using

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nikhil-001mehta/angular-2-daterangepicker/issues/29#issuecomment-397800238>,
or mute the thread

**Comment by nikhil-001mehta** [comment] 2018-06-16 13:44
@sapanjwani Thanks a lot for pointing out the issue i have fixed the issue in v1.1.43. Let me know if you have any sugestions or facing any issues.
