### ISSUE TITLE
daterangepicker-module.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by tagolito** [nikhil-001mehta/angular-2-daterangepicker#24] opened 2018-01-08 18:48 UTC
ERROR in ./node_modules/angular-2-daterangepicker/daterangepicker-options.ts
Module build failed: Error: C:\mypath\node_modules\angular-2-daterangepicker\daterangepicker-module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

I followed the instructions to install. after adding it up in the module, this error showed up.
Im using angular5 now.

**Comment by nikhil-001mehta** [comment] 2018-03-22 17:30
Closing this issue. Added a fix will be released in next version.

**Comment by nikhil-001mehta** [comment] 2018-03-22 19:08
Closing this issue. Added a fix will be released in next version.

**Comment by nikhil-001mehta** [comment] 2018-03-22 19:08
Closing this issue. Added a fix will be released in next version.

**Comment by MFava91** [comment] 2018-04-30 22:44
Hi @nikhil-001mehta , 
it seems that the problem is not solved yet (I've tried version 1.1.31 with angular-cli 1.7.4).
For those wondering how to get a workaround for this problem, just need to add this lines of code on `tsconfig.json`:
```
    "include": [
        "src/**/*",
        "node_modules/angular-2-daterangepicker/index.ts"
    ]
```
I think that this is a big problem for those who try this module for the first time.

Example of full `tsconfig.json`:
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom"
        ]
    },
    "include": [
        "src/**/*",
        "node_modules/angular-2-daterangepicker/index.ts"
    ]
}
```

**Comment by nikhil-001mehta** [comment] 2018-05-01 18:09
@MFava91 Will look into it on priority. Opening the issue again to keep track

**Comment by MFava91** [comment] 2018-05-01 21:47
@nikhil-001mehta  Work perfectly (version **1.1.32** with angular-cli **1.7.4** - Angular **5.2.10**).
Nice work 👍

**Comment by nikhil-001mehta** [comment] 2018-05-05 06:02
@MFava91 Thanks a lot. Closing the issue.

**Closed by nikhil-001mehta** 2018-05-05 06:02 UTC

**Comment by MFava91** [comment] 2018-05-07 21:46
@nikhil-001mehta it seems that the problem reappeared in version **1.1.36**.
```
ERROR in ./node_modules/angular-2-daterangepicker/daterangepicker-module.ts
Module build failed: Error: C:\Users\Mattia\testDateRange\node_modules\angular-2-daterangepicker\daterangepicker-module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Mattia\testDateRange\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Mattia\testDateRange\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
ERROR in ./node_modules/angular-2-daterangepicker/daterangepicker-options.ts
Module build failed: Error: C:\Users\Mattia\testDateRange\node_modules\angular-2-daterangepicker\daterangepicker-options.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Mattia\testDateRange\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Mattia\testDateRange\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by nikhil-001mehta** [comment] 2018-05-08 18:05
@MFava91 I have fixed it in v.1.1.37 Let me know if you find it useful. Thanks

**Comment by MFava91** [comment] 2018-05-08 22:01
@nikhil-001mehta Work nice 👍
